version: '3.4'

services:
  bobmicro:
    image: bobmicro
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5187:80"
    networks:
      - sharednetwork

networks:
  sharednetwork:
    driver: bridge
